// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmvbnbdquouifyavaixn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tdmJuYmRxdW91aWZ5YXZhaXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzg0MDEsImV4cCI6MjA3MTgxNDQwMX0.SM8H9opwsTnMEESsuxaNdNjcUIpJq7nt8MGN05i44Qo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});